### ISSUE TITLE
Idea of implementation in Chromium browser

### ISSUE THREAD

**Issue by wong2** [matusfaro/quarantab#4]
I think this can be implemented in Chromium browsers with the [`declarativeNetRequest`](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest) API and [`initiatorDomains`](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#property-RuleCondition-initiatorDomains) condition, which allows you to block all network requests initialized by a specific domain.

**Comment by matusfaro** [comment]
Thank you @wong2 for the suggestion. The other two problems to solve are:
1. Preventing a website from communicating with other websites currently open in other tabs, even on the same domain. This would mean isolating local storage, cookies, broadcast channel, etc... This could utilize the Private window potentially that works similarly to a Firefox Container
2. Deleting all leftover website data after you are finished with the website. Otherwise the website could phone home after we lift the network block at a later time. Again this could potentially utilize the Private window, but would need to be able to control this from the extension.
